/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HeaderEntry {
  key: string
  value: string
}
export interface ParsedRequest {
  method: string
  path: string
  version: string
  headers: Array<HeaderEntry>
}
export declare function parseHttp(raw: Buffer): ParsedRequest
